### ISSUE TITLE
Reload Crash, Loading Errors, and Parsing Time

### ISSUE THREAD

**Issue by Baezor1** [JacobJoergensen/TablistManager#18]
## Loading Errors
When SkBee is installed, errors occur when the script loads.
![Screen Shot 2022-10-16 at 10 33 20 AM](https://user-images.githubusercontent.com/64096464/196044117-c39ae384-2794-44f6-be40-e9caae3080a7.png)
## Server Crash
When reloading the script in game, it crashes my server. (This error goes on for awhile.)
![Screen Shot 2022-10-16 at 10 34 11 AM](https://user-images.githubusercontent.com/64096464/196044155-1c8eb1e5-3682-47a7-89fa-95a3499f7185.png)
## Parsing Time
In addition to all of this, it takes an incredibly long time to parse. Some research needs to be done on how to improve the time.

**Comment by JacobJoergensen** [comment]
Thank you, that is weird, I will do some investigation and testing later today.

**Comment by JacobJoergensen** [comment]
I have implemented a fix in the newest version 1.0.1, this should give you better performance when SkBee is installed. The problem was that if you had SkBee on your server, it would create a parsing issue with the TablistManager code. But this fix should fix it. It works for me now when I have SkBee. (the crashing should also be gone). Have tested this with the latest version of SkBee 2.3.3.

About the two errors you get in your console, do you have all addons installed? 
You need to have: skript-reflect, skript-yaml, vault and a group plugin (luckperms, groupmanager, permissionex etc.) on your server.

Try the new version and please let me know if it all works for you now? :)
